'use client';

import { signIn } from 'next-auth/react';
import { Zap, CheckCircle } from 'lucide-react';
import styles from './login.module.css';

const FEATURES = [
  'AI-powered ATS Resume Checker',
  'ATS-Friendly Resume Builder',
  'Job Description Matcher',
  'AI Resume Tailoring & Cover Letters',
];

export default function LoginPage() {
  return (
    <div className={styles.page}>
      {/* Left panel */}
      <div className={styles.left}>
        <div className={styles.leftContent}>
          <div className={styles.logo}>
            <div className={styles.logoIcon}>
              <Zap size={24} />
            </div>
            <span className={styles.logoText}>ResumeAI</span>
          </div>

          <h1 className={styles.headline}>
            Land more interviews with an
            <br />
            <span className={styles.accent}>ATS-optimized resume</span>
          </h1>

          <p className={styles.subheadline}>
            Build, check, and tailor your resume with AI. Get real ATS compatibility
            scores and actionable improvement recommendations.
          </p>

          <ul className={styles.features}>
            {FEATURES.map((f) => (
              <li key={f} className={styles.feature}>
                <CheckCircle size={16} className={styles.checkIcon} />
                <span>{f}</span>
              </li>
            ))}
          </ul>

          <p className={styles.disclaimer}>
            * ATS Compatibility Score is generated by this application and does not represent
            the proprietary scoring system of any specific ATS vendor.
          </p>
        </div>
      </div>

      {/* Right panel */}
      <div className={styles.right}>
        <div className={styles.card}>
          <div className={styles.cardHeader}>
            <h2 className={styles.cardTitle}>Sign in to ResumeAI</h2>
            <p className={styles.cardSubtitle}>Start building your best resume today</p>
          </div>

          <button
            className={styles.googleBtn}
            onClick={() => signIn('google', { callbackUrl: '/dashboard' })}
            id="sign-in-google"
          >
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none">
              <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/>
              <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/>
              <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"/>
              <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/>
            </svg>
            Continue with Google
          </button>

          <div style={{ marginTop: '1rem', textAlign: 'center' }}>
            <span style={{ fontSize: '0.875rem', color: 'var(--text-secondary)' }}>or for testing:</span>
          </div>
          
          <button
            className={styles.googleBtn}
            style={{ marginTop: '0.5rem', background: 'var(--bg-elevated)', border: '1px solid var(--border)', color: 'var(--text-primary)' }}
            onClick={() => signIn('credentials', { email: 'demo@example.com', password: 'password', callbackUrl: '/dashboard' })}
            id="sign-in-demo"
          >
            One-Click Demo Login
          </button>

          <p className={styles.terms}>
            By signing in, you agree to our{' '}
            <a href="#" className={styles.link}>Terms of Service</a> and{' '}
            <a href="#" className={styles.link}>Privacy Policy</a>.
            Your resume data is processed securely and never shared.
          </p>
        </div>
      </div>
    </div>
  );
}
